Repository adobe/commerce-cif-connector, pull requests merged in 2020-02, with the labels that each got.

#91 CIF-1227 - Update Connector GraphQL queries for Magento 2.3.4 Schema
  .circleci/ci/it-tests.js
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImpl.java
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/category-products.txt
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/products-empty-search-for-category.txt
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/products-empty-search.txt
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/products-search-for-category.txt
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/products-search.txt
  parent/pom.xml
Labels: To Verify, enhancement

#92 CIF-1230 - CIF "omnisearch" has a pagination issue
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/GraphqlQueryLanguageProvider.java
Labels: Verified, bug

#99 CIF-1247 - Product Picker bug
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlQueries.java
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/category-products.txt
Labels: Verified, bug

#100 CIF-1283 - [AEM Connector] Collect all GraphQL queries generated by u…
  bundles/cif-connector-graphql/pom.xml
  bundles/cif-connector-graphql/src/test/resources/logback-test.xml
  bundles/cif-connector-graphql/src/test/resources/simplelogger.properties
  bundles/cif-connector-graphql/src/test/resources/test-queries/README.md
  bundles/cif-connector-graphql/src/test/resources/test-queries/graphql-requests.log
  parent/pom.xml
Labels: To Verify

#101 CIF-1285 - Product search is slow in product console and product picker
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/core/GraphqlProductViewHandler.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/core/MagentoProduct.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImpl.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/core/GraphqlProductViewHandlerTest.java
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/products-empty-search-for-category.txt
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/products-empty-search.txt
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/products-search-for-category.txt
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/products-search.txt
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/content/common/cifproductfield/picker/.content.xml
Labels: bug

#102 CIF-1286 - Search support in category picker
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataService.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImpl.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlQueries.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/CategoryResource.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/GraphqlQueryLanguageProvider.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/gui/components/common/cifproductfield/impl/SearchDataSourceServlet.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImplTest.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/resource/GraphqlQueryLanguageProviderTest.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/gui/components/common/cifproductfield/impl/SearchDataSourceServletTest.java
  bundles/cif-connector-graphql/src/test/resources/commerce-categories-omnisearch-request.json
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/category-search.txt
  bundles/cif-connector-graphql/src/test/resources/magento-graphql-category-search.json
  bundles/cif-connector-graphql/src/test/resources/test-queries/graphql-requests.log
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifcategoryfield/carditem/carditem.html
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/content/common/cifcategoryfield/picker/.content.xml
Labels: enhancement
