Repository adobe/commerce-cif-connector, pull requests merged in 2020-03, with the labels that each got.

#104 @trivial - update versions
  README.md
  VERSIONS.md
Labels: releng

#97 CIF-1134 - Unified configuration of site settings
  README.md
  bundles/cif-connector-graphql/pom.xml
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/GraphqlQueryLanguageProvider.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/GraphqlResourceProvider.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/GraphqlResourceProviderFactory.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/ResourceMapper.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/gui/components/configuration/ConfigurationColumnPreview.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/gui/components/configuration/ConfigurationColumnViewItem.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/magento/GraphqlAemContext.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/resource/GraphqlResourceProviderFactoryTest.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/resource/GraphqlResourceProviderTest.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/gui/components/configuration/ConfigurationColumnPreviewTest.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/gui/components/configuration/ConfigurationColumnViewItemTest.java
  bundles/cif-connector-graphql/src/test/resources/context/graphql-client-adapter-factory-context.json
  bundles/cif-connector-graphql/src/test/resources/context/jcr-conf-console.json
  bundles/cif-connector-graphql/src/test/resources/context/jcr-conf.json
  bundles/cif-connector-graphql/src/test/resources/test-queries/graphql-requests.log
  bundles/cif-virtual-catalog/pom.xml
  bundles/cif-virtual-catalog/src/main/java/com/adobe/cq/commerce/virtual/catalog/data/Constants.java
  bundles/cif-virtual-catalog/src/main/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataResourceProviderManagerImpl.java
  bundles/cif-virtual-catalog/src/test/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataProviderManagerConfTest.java
  bundles/cif-virtual-catalog/src/test/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataResourceProviderManagerImplTest.java
  bundles/cif-virtual-catalog/src/test/resources/context/jcr-conf.json
  bundles/cif-virtual-catalog/src/test/resources/context/jcr-dataroots.json
  content/cif-connector/src/main/content/META-INF/vault/filter.xml
  content/cif-connector/src/main/content/jcr_root/apps/commerce/gui/content/products/bindproducttreewizard/.content.xml
  content/cif-connector/src/main/content/jcr_root/apps/commerce/gui/content/products/bindproducttreewizard/customfields/.content.xml
  content/cif-connector/src/main/content/jcr_root/apps/commerce/gui/content/products/bindproducttreewizard/customfields/magento-graphql/.content.xml
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/clientlibs/configbrowser/.content.xml
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/clientlibs/configbrowser/js.txt
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/clientlibs/configbrowser/js/actions/delete.js
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/clientlibs/configbrowser/js/renderconditions/hascommerceconfig.js
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/columnpreview/columnpreview.html
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/columnviewitem/columnviewitem.html
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/.content.xml
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/_cq_dialog/.content.xml
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/clientlibs/.content.xml
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/clientlibs/css.txt
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/clientlibs/css/configurationpage.css
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/clientlibs/js.txt
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/clientlibs/js/configurationpage.js
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/template/.content.xml
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/content/configuration/.content.xml
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/content/configuration/createconfiguration/.content.xml
  content/cif-connector/src/main/content/jcr_root/libs/cq/core/content/nav/tools/cloudservices/cifconfig/.content.xml
  content/cif-virtual-catalog/src/main/content/jcr_root/libs/commerce/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-virtual-commerce.xml
  content/cif-virtual-catalog/src/main/content/jcr_root/libs/commerce/gui/content/products/bindproducttreewizard/.content.xml
  parent/pom.xml
Labels: To Verify, enhancement

#105 CIF-1182 - Use the same property type in components with product DnD
  README.md
  bundles/cif-connector-graphql/pom.xml
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/postprocessor/MultiFieldDropTargetPostProcessor.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/postprocessor/MultiFieldDropTargetPostProcessorTest.java
  bundles/cif-connector-graphql/src/test/resources/context/drop-target-post-processor.json
  bundles/cif-connector-graphql/src/test/resources/logback-test.xml
Labels: To Verify, enhancement

#98 CIF-1245 - Connector fails if Magento GraphQL response has errors.
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/Constants.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/ErrorResource.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/ResourceMapper.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/resource/GraphqlResourceProviderTest.java
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifcategoryfield/CIFCategoryFieldHelper.java
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifproductfield/CIFProductFieldHelper.java
  content/cif-virtual-catalog/src/main/content/jcr_root/libs/commerce/gui/components/admin/products/childcard/childcard.jsp
  content/cif-virtual-catalog/src/main/content/jcr_root/libs/commerce/gui/components/admin/products/childcolumnitem/childcolumnitem.jsp
  content/cif-virtual-catalog/src/main/content/jcr_root/libs/commerce/gui/components/admin/products/childrow/childrow.jsp
Labels: bug

#108 CIF-1330 - GraphQL endpoint used by client-side code should be configurable
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/_cq_dialog/.content.xml
Labels: To Verify, enhancement

#111 CIF-1336 - CIF Connector build fails on Windows
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/core/GraphqlProductViewHandlerTest.java
Labels: Verified, bug
