Repository adobe/commerce-cif-connector, pull requests merged in 2020-04, with the labels that each got.

#115 Clean up cloud services config dialog
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/_cq_dialog/.content.xml
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/clientlibs/js/configurationpage.js
Labels: Verified, enhancement

#114 CIF-1287 - Filling the category cache is slow
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataService.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceConfiguration.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImpl.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlQueries.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/CategoryResource.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/GraphqlResourceProvider.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/GraphqlResourceProviderFactory.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/ResourceMapper.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImplTest.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/magento/MockGraphqlDataServiceConfiguration.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/magento/TestList.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/resource/GraphqlResourceProviderFactoryTest.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/resource/GraphqlResourceProviderTest.java
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/categorylist-by-urlkey.txt
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/root-category.txt
  bundles/cif-connector-graphql/src/test/resources/magento-graphql-category-tree-2.3.1.json
  bundles/cif-connector-graphql/src/test/resources/magento-graphql-categorylist-coats.json
  bundles/cif-connector-graphql/src/test/resources/magento-graphql-categorylist-dresses.json
  bundles/cif-connector-graphql/src/test/resources/magento-graphql-categorylist-empty.json
  bundles/cif-connector-graphql/src/test/resources/magento-graphql-categorylist-root.json
  bundles/cif-connector-graphql/src/test/resources/test-queries/graphql-requests.log
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifcategoryfield/CIFCategoryFieldHelper.java
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifproductfield/ViewHelper.java
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/content/common/cifcategoryfield/picker/.content.xml
  content/cif-virtual-catalog/src/main/content/jcr_root/libs/commerce/gui/components/admin/products/childcard/childcard.jsp
  content/cif-virtual-catalog/src/main/content/jcr_root/libs/commerce/gui/components/admin/products/childcolumnitem/childcolumnitem.jsp
  content/cif-virtual-catalog/src/main/content/jcr_root/libs/commerce/gui/components/admin/products/childrow/childrow.jsp
  it/http/src/test/java/com/adobe/cq/commerce/it/http/GraphqlProductConsoleIT.java
  it/http/src/test/resources/com/adobe/cq/commerce/it/http/magento-graphql-category-tree-2.3.1.json
  it/http/src/test/resources/com/adobe/cq/commerce/it/http/magento-graphql-categorylist-coats.json
  it/http/src/test/resources/com/adobe/cq/commerce/it/http/magento-graphql-categorylist-empty.json
  it/http/src/test/resources/com/adobe/cq/commerce/it/http/magento-graphql-categorylist-men.json
  it/http/src/test/resources/com/adobe/cq/commerce/it/http/magento-graphql-categorylist-root.json
Labels: Verified, enhancement

#118 CIF-1347 - Product Console doesn't display products
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/Constants.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/GraphqlResourceProviderFactory.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/resource/GraphqlResourceProviderFactoryTest.java
  bundles/cif-connector-graphql/src/test/resources/context/jcr-conf.json
Labels: bug

#120 Update readme.md for AMS deplyoment
  README.md
Labels: releng
