Repository adobe/commerce-cif-connector, pull requests merged in 2020-11, with the labels that each got.

#156 Update README.md
  README.md
Labels: releng

#155 CIF-1713 - [CIF Connector] Add support for urlPath property in catego…
  README.md
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/CategoryResource.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/Constants.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/resource/GraphqlResourceProviderTest.java
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifcategoryfield/CIFCategoryFieldHelper.java
Labels: Verified, enhancement

#158 CIF-1528 - CIF CloudConfig console should display replication info on cards
  bundles/cif-connector-graphql/pom.xml
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/gui/components/configuration/ConfigurationColumnPreview.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/gui/components/configuration/package-info.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/gui/components/configuration/ConfigurationColumnPreviewTest.java
  bundles/cif-connector-graphql/src/test/resources/context/jcr-conf-console.json
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/columnpreview/columnpreview.html
  parent/pom.xml
Labels: enhancement
