Repository adobe/commerce-cif-connector, pull requests merged in 2020-05, with the labels that each got.

#123 CIF-1377 - NPE when connector configuration is installed via content …
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImpl.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImplTest.java
Labels: To Verify, bug

#119 CIF-1327 - Show a "Create configuration folder" action in the CIF Configuration console
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/gui/components/configuration/ConfigurationColumnViewItem.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/gui/components/configuration/ConfigurationColumnPreviewTest.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/gui/components/configuration/ConfigurationColumnViewItemTest.java
  bundles/cif-connector-graphql/src/test/resources/context/jcr-conf-console.json
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/clientlibs/configbrowser/js.txt
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/clientlibs/configbrowser/js/renderconditions/renderconditions.js
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/columnviewitem/columnviewitem.html
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/content/configuration/.content.xml
Labels: enhancement

#126 CIF-1393 - Automatic product binding creation fails
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/omnisearch/ProductsSuggestionOmniSearchHandler.java
  bundles/cif-connector-graphql/src/test/resources/test-queries/graphql-requests.log
  bundles/cif-virtual-catalog/src/main/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataResourceProviderManagerImpl.java
  bundles/cif-virtual-catalog/src/main/java/com/adobe/cq/commerce/virtual/catalog/data/impl/ProductBindingCreator.java
  bundles/cif-virtual-catalog/src/test/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataProviderManagerConfTest.java
  bundles/cif-virtual-catalog/src/test/java/com/adobe/cq/commerce/virtual/catalog/data/impl/ProductBindingCreatorTest.java
Labels: Verified, bug

#127 CIF-1401 - Copyright info in HTML source of product picker and category picker
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifcategoryfield/carditem/carditem.html
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifcategoryfield/cifcategoryfield.html
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifcategoryfield/columnitem/columnitem.html
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifcategoryfield/columnitempreview/columnitempreview.html
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifcategoryfield/listitem/listitem.html
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifproductfield/carditem/carditem.html
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifproductfield/cifproductfield.html
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifproductfield/columnitem/columnitem.html
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifproductfield/columnitempreview/columnitempreview.html
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifproductfield/listitem/listitem.html
  content/cif-virtual-catalog/src/main/content/jcr_root/libs/commerce/components/cifimage/cifimage.html
Labels: bug
