Repository adobe/commerce-cif-connector, pull requests merged in 2020-01, with the labels that each got.

#83 releng - Update QP docker image to 6.4.4
  .circleci/config.yml
Labels: releng

#82 CIF-1190 - The "project" field from the Binding Wizard has an incorre…
  content/cif-virtual-catalog/src/main/content/jcr_root/libs/commerce/components/cifrootfolder/_cq_dialog/.content.xml
  content/cif-virtual-catalog/src/main/content/jcr_root/libs/commerce/gui/content/products/bindproducttreewizard/.content.xml
Labels: Verified, bug

#81 CIF-1195 - Several performance improvements in CIF pickers and product console
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImpl.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlQueries.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/CategoryResource.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/resource/ProductResource.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImplTest.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/resource/GraphqlResourceProviderTest.java
  bundles/cif-connector-graphql/src/test/resources/graphql-queries/category-products.txt
  bundles/cif-connector-graphql/src/test/resources/magento-graphql-category-tree-2.3.1.json
  bundles/cif-connector-graphql/src/test/resources/magento-graphql-other-product.json
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifproductfield/CIFProductFieldHelper.java
  content/cif-virtual-catalog/src/main/content/jcr_root/libs/commerce/gui/components/admin/products/childcard/childcard.jsp
  content/cif-virtual-catalog/src/main/content/jcr_root/libs/commerce/gui/components/admin/products/childcolumnitem/childcolumnitem.jsp
Labels: Verified, enhancement

#89 CIF-1206 - [Github #88] Connector caches MUST include the store view header value
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImpl.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImplTest.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/graphql/magento/MockGraphqlDataServiceConfiguration.java
  parent/pom.xml
Labels: Verified, bug
