Repository adobe/commerce-cif-connector, pull requests merged in 2020-07, with the labels that each got.

#131 CIF-1446: Preview with Product in page editor - preview URL must conform to UrlProvider configuration
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/authoring/editor/pagepreview/clientlibs/pagepreview.js
  content/cif-connector/tests/src/libs/commerce/gui/components/authoring/editor/pagepreview/PagePreviewTest.js
  content/cif-connector/tests/src/libs/commerce/gui/components/common/cifpicker/CifPickerTest.js
Labels: bug

#137 CIF-1485 - The cq:catalogPath restriction not applied to picker when previewing non-empty page
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/renderconditions/IsProductDetailPageServlet.java
Labels: Verified, bug

#139 CIF-1508 - Add Publish/Un-publish action CIF CloudConfig UI
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/gui/components/configuration/ConfigurationColumnViewItem.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/gui/components/configuration/ConfigurationColumnViewItemTest.java
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/content/configuration/.content.xml
Labels: To Verify, enhancement

#140 CIF-1496 - Add clientlib dependencies for pickers to README
  README.md
Labels: To Verify

#143 Show inherited configuration properties in the UI
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/gui/components/configuration/servlets/ConfigurationInheritanceServlet.java
  bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/utils/ConfigInheritance.java
  bundles/cif-connector-graphql/src/test/java/com/adobe/cq/commerce/gui/components/configuration/servlets/ConfigurationInheritanceServletTest.java
  bundles/cif-connector-graphql/src/test/resources/context/jcr-conf-inheritance.json
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/_cq_dialog/.content.xml
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/clientlibs/css/configurationpage.css
  content/cif-connector/src/main/content/jcr_root/libs/commerce/gui/components/configuration/page/clientlibs/js/configurationpage.js
Labels: Verified
